### ISSUE TITLE
offline mirror should contain latest_specs.4.8.gz and latest_specs.4.8

### ISSUE THREAD

**Issue by kfirlavi** [rubygems/rubygems-mirror#32] opened 2015-04-27 11:49 UTC
Hi
The latest code will download this files:
```bash
specs.4.8.gz
specs.4.8
prerelease_specs.4.8.gz
prerelease_specs.4.8
```
But this files are missing and needed by `gem install`:
```bash
latest_specs.4.8.gz
latest_specs.4.8
```

To solve this, I have created a link:
```bash
cd /offline_gem_repo/gems/
ln -s specs.4.8.gz latest_specs.4.8.gz
ln -s specs.4.8 latest_specs.4.8
```
I'm not sure this files needs to be downloaded, but creating the soft links solves my gem install problem.

Regards,
@kfirlavi

**Comment by raggi** [comment] 2015-04-27 21:26
So you'd typically be able to fix this by just running `gem index`, happy to accept patches to pull these files or to optionally run index for the user at the end of a mirror.

**Comment by kfirlavi** [comment] 2015-04-28 07:21
It seems that generating the index is a heavy task:
```
 gem generate_index -d /offline_gem_repo/gems/
```
I would prefer to go with a symlink, but is it a good solution?

**Comment by kfirlavi** [comment] 2015-04-28 12:20
```
gem generate_index -d /mnt/storage/mirror/ruby/gems --update -V
``` 
takes 30 seconds, but I get the same error that we started with:
```
...
285/287: zotplus-rakehelper-0.0.79
286/287: zotplus-rakehelper-0.0.78
287/287: zotplus-rakehelper-0.0.77
Complete
Generated Marshal quick index gemspecs: 0.260s
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory - /mnt/storage/mirror/ruby/gems/latest_specs.4.8
```

**Comment by pjump** [comment] 2015-05-11 15:10
@kfirlavi you can download it from the source url, e.g.:
wget https://www.rubygems.org/latest_specs.4.8.gz
OR
wget http://production.cf.rubygems.org/latest_specs.4.8.gz 
and gunzip afterwards.

**Comment by facastagnini** [comment] 2015-07-27 22:17
I am experiencing the same issue. 
The symlink solution did not work for me, I am testing `gem generate_index -V`

**Comment by facastagnini** [comment] 2015-07-28 17:57
After dealing with this problem for a while I find out that the problem is that the version 1.0.1 is too old.
Cloning from master and running `rake mirror:update` give me a usable repo.

**Comment by raggi** [comment] 2015-07-28 19:07
I believe this is fixed in 1.1.0

**Closed by raggi** 2015-07-28 19:07 UTC

**Comment by miguelsantos500** [comment] 2017-09-11 13:00
@pjump I know I'm a little late, but what do you mean by gunzip? What do I do with the file? Thanks in advance.

**Comment by pskocik** [comment] 2017-09-11 13:18
@miguelsantos500 Unix command for uncompressing gzip-compressed data. Search engines are your friends.

**Comment by miguelsantos500** [comment] 2017-09-11 13:19
@pjump I know what it does, but i don't know what to do with the file after I uncompress it.

**Comment by raggi** [comment] 2017-09-11 15:01
It's in Marshal 4.8 format and can be de-serialized by the standard library `Marshal.load`
